# -*- coding: utf-8 -*-
"""Form V3 Macenko Cross Validation Dataset

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TeStzjyr3LawWY1bUvM3oi6_zCekP-QL
"""

# import library
import numpy as np
import os
import PIL
import PIL.Image
import tensorflow as tf
import matplotlib.pyplot as plt
from google.colab import drive
import pandas as pd
from keras_preprocessing.image import ImageDataGenerator
from sklearn.utils import shuffle 
import sklearn
import sklearn.model_selection

# connect to drive
drive.mount('/content/drive')

base_path = '/content/drive/MyDrive/Wingates FYP/Dataset/V3 Macenko Normalised IDC Grading Dataset/Training Set'

# Get img file path
from fastai import *
from fastai.vision import *
path = Path(base_path)
file_path=get_files(path, recurse=True)
print(len(file_path)) # To validate equal total number of images

# Create a dataframe from the file path with class
pd.set_option("display.max_colwidth", 0)
data = pd.DataFrame(index=np.arange(0, len(file_path)), columns=["path", "grade"])
count = 0

for image_path in file_path:
  path_name = str(image_path)
  grade = str(path_name[99:106])
  
  
  
  data.iloc[count]["path"] = path_name
  
  data.iloc[count]["grade"] = grade

  count +=1

data.head()

# check for classes
data.grade.unique()

# check for dataframe shape
data.shape

# shuffle the dataframe
data = shuffle(data)
data.head()

# get the data frame label
Y = data[['grade']]
Y

# initiliase stratifield kfold  
skf = sklearn.model_selection.StratifiedKFold (n_splits = 5, random_state = 123, shuffle = True)

# create dataframe for each fold and save into csv file
i = 1
for train_index, val_index in skf.split(np.zeros(len(data)),Y):
 training_data = data.iloc[train_index]
 validation_data = data.iloc[val_index]

 training_data.to_csv(f'/content/drive/MyDrive/Wingates FYP/CSV2/V3_SN_M_training_data_400x{i}.csv')
 validation_data.to_csv(f'/content/drive/MyDrive/Wingates FYP/CSV2/V3_SN_M_validation_data_400x{i}.csv')
 i+=1